### ISSUE TITLE
Installer ends with error

### ISSUE THREAD

**Issue by bfg9000it** [deadhead420/anarchy-linux#795] opened 2019-06-01 14:13 UTC
![immagine](https://user-images.githubusercontent.com/30441992/58749580-1852a980-8488-11e9-813a-da35dbb5bf6c.png)
file conflict during installation as shown in the picture

**Comment by PandaFoss** [comment] 2019-06-01 15:38
This error was solved [here](https://github.com/deadhead420/anarchy-linux/issues/794#issuecomment-497812764).

**Comment by bfg9000it** [comment] 2019-06-01 19:26
Thank you and sorry for the dup

Il sab 1 giu 2019, 17:38 Max Ferrer <notifications@github.com> ha scritto:

**Comment by PandaFoss** [comment] 2019-06-01 19:29
If the issue is solved, I advise to close it.

**Comment by bfg9000it** [comment] 2019-06-01 20:03
For me no. I've tested the two workaround suggested before the installation
but at the end there is the same error

Il sab 1 giu 2019, 21:29 Max Ferrer <notifications@github.com> ha scritto:

**Comment by PandaFoss** [comment] 2019-06-01 20:17
Did you accidentally update Anarchy with the `anarchy -u` command after carrying out the proposed solutions? If you want to update Anarchy, you must do it **before** doing what I propose in the previous comment.
If it still does not work and the error is exactly the same as it appears in the screenshot, try the following before starting the installer:
**1.** `# nano /etc/anarchy.conf`
**2.** Remove `arch-wiki-cli` on line 185
**3.** Run `# anarchy`
If it does not work, share a screenshot with the new error please.

**Comment by bfg9000it** [comment] 2019-06-01 20:54
Now It's ok. Thanks.
Removing " arch-wiki-cli" entry from " /etc/anarchy.conf" and the file "
/usr/share/pixmaps/archlinux.png" before starting anarchy installer.

Il giorno sab 1 giu 2019 alle ore 22:17 Max Ferrer <notifications@github.com>
ha scritto:

**Comment by PandaFoss** [comment] 2019-06-03 22:03
@bfg9000it If the issue is solved, I advise to close it.

**Comment by bfg9000it** [comment] 2019-06-04 17:29
For me (removing package entry on anarchy.conf) issue has been resolved.
Thank you.

Il giorno mar 4 giu 2019 alle ore 00:03 Max Ferrer <notifications@github.com>
ha scritto:

**Comment by batmanm0b1E** [comment] 2019-06-07 02:42
I have run the anarchy installer 5 to 10 times with the same output at the end it errors everytime
with that exact same output.

**Comment by batmanm0b1E** [comment] 2019-06-07 03:23
ok i did this stated above

1. # nano /etc/anarchy.conf
2. Remove arch-wiki-cli on line 185

and it worked

please fix in next ISO please really needs to be fixed... Its supposed to be easy to use anarchy installer right now its botched

**Closed** 2019-06-08 07:03 UTC
