### ISSUE TITLE
Pacman issues after downloading packages

### ISSUE THREAD

**Issue by jesusrp98** [deadhead420/anarchy-linux#794] opened 2019-05-31 10:54 UTC
I'm having issues trying to install Anarchy Linux, in both real hardware & virtual enviroments. I've tried both LTS & non-LTS versions of the OS.

## Steps to reproduce:
* Select country & language as normal.
* Selecting the LTS or non-LTS release (it doesn't matter).
* Input both root & normal users.
* Don't select any extra program to install.

Here are the `/tmp/anarchy.log` files:

### LTS screenshot:
![Screenshot from 2019-05-31 14-25-18](https://user-images.githubusercontent.com/8961959/58701172-8624a580-83a2-11e9-925b-9a5bd5061350.png)

### Non-LTS screenshot:
![Screenshot from 2019-05-31 12-48-15](https://user-images.githubusercontent.com/8961959/58701189-8cb31d00-83a2-11e9-970c-17e8a2312855.png)

As you can see, the issue is basically the same in both versions.

**Comment by PandaFoss** [comment] 2019-05-31 16:03
Before starting the installation, I recommend the following:
**1.** Run `anarchy -u`
**2.** Then `anarchy -k`
**3.** And finally `fetchmirrors` (to update mirrors)
Once you start the installation, skip the mirror update.

**Comment by jesusrp98** [comment] 2019-05-31 17:37
Done that, but unfortunately it keeps failing. However, it looks like the error has change. Here's the screenshot.

![Screenshot from 2019-05-31 19-04-16](https://user-images.githubusercontent.com/8961959/58723884-770e1980-83db-11e9-8405-87df9fdb5766.png)

**Comment by PandaFoss** [comment] 2019-05-31 18:23
This happens because in the Arch Linux [update of 2019-05-02](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/filesystem&id=ad1d579394a73790c2c1759edb6f48d70d764029) the logo `archlinux.png` is incorporated and when `arch-wiki-cli` wants to install it, the conflict is generated.
However, it has just been solved [here](https://github.com/deadhead420/arch-wiki/commit/6ff0424c4f12cd4f493eab28e6dff651fbff2893). The problem is that the ISO image was generated with the old version of `arch-wiki-cli`. Try removing the file before starting the installation as follows:

`# rm /usr/share/pixmaps/archlinux.png`

Another possible solution is to remove the package with `pacman -Rsn arch-wiki-cli` and reinstall it once inside the installed system with `yay`, `aurman` or the AUR Helper of your choice.

I hope you are lucky! I wait your answer.

**Comment by jesusrp98** [comment] 2019-05-31 20:03
That solved the issue!! Thank you very much!!
You really helped me a lot, now it's time to enjoy Anarchy Linux :)

**Comment by PandaFoss** [comment] 2019-05-31 23:52
@jesusrp98 de nada hermano! Jajajaja
If the issue is solved, I advise to close it.

**Closed** 2019-06-01 10:36 UTC
