### ISSUE TITLE
pacman fails on system installation begin

### ISSUE THREAD

**Issue by mbalc** [deadhead420/anarchy-linux#753] opened 2018-11-04 18:16 UTC
After doing all the configurations in the `anarchy` installer on the newest `v1.0.1` version of the CLI installer on a fresh Virtualbox instance (Windows 10 host, shouldn't matter) and on starting the main installation process - it fails immediately, telling to check `/tmp/anarchy.log`, which contains the following error for `pacman` command usage at its end:

```
==> Installing packages to /mnt
warning: option --force is deprecated; use --overwrite instead
error: invalid option '-f'
==> ERROR: Failed to install packages to new root
2018-11-04 18:15 : Install failed: please report to developer
```

![image](https://user-images.githubusercontent.com/11033790/47968143-ea2df800-e065-11e8-85ab-f42f6e34db8f.png)
![image](https://user-images.githubusercontent.com/11033790/47968151-ffa32200-e065-11e8-94f1-3ce80b57d227.png)
![image](https://user-images.githubusercontent.com/11033790/47968156-0b8ee400-e066-11e8-836e-9a3b999fdc76.png)
![image](https://user-images.githubusercontent.com/11033790/47968160-177aa600-e066-11e8-9d0c-14235f1cf3d0.png)

**Comment by drzeeb** [comment] 2018-11-05 18:08
You have to execute
pacman -S archlinux-keyring
before installation

**Comment by b92we** [comment] 2018-11-08 15:22
i got the same error if i choose lts kernel.
i think the problem is in [install_base.sh](https://github.com/deadhead420/anarchy-linux/blob/923a4d9717f6ac08507e51479523aa841b960e31/lib/install_base.sh#L46) line 46.
..maybe replace the `sed 's/^linux//'` with `sed 's/^linux$/&-lts/'` (can't try it today)

did u try installing without lts? :P

**Comment by sundowndev** [comment] 2018-11-11 16:49
Having the same issue. It works well without LTS.

**Comment by Spheerys** [comment] 2018-11-16 13:51
I had the same behavior.
I pass the install with : 
- pacman -Sy
- pacman -S archlinux-keyring
- anarchy -u
- anarchy
- select advanced installation, only i3, no additionnal packages and no-LTS kernel (base).

I guess there is something wrong with LTS kernel or maybe the archlinux-keyring package ?

**Comment by Mayurifag** [comment] 2018-12-11 19:34
Having similar problem. Trying GUI installer in Virtualbox to install Arch with Zen kernel. 

Steps to reproduce:
1) Boot GUI, Fetchmirrors
2) Terminal: `sudo pacman -Sy`, `sudo pacman -S archlinux-keyring`, `sudo anarchy -u`
3) Launch GUI installer:
- English language; us keymap; en_US.UTF-8 locale; GMT timezone
- Autopartition ext4 without swap and GPT 
- Anarchy-Advanced: Arch-Linux-Zen-Devel
- bash; grub; networkmanager; multilib added; DHCP at boot; no wifi, PPPOE, os-prober (just hitted enter to keep everything default)
- Desktop environment: customized -> Anarchy-cinnamon 
- virtualbox-guest-utils installing because Virtualbox detected
- no xf86-input (touchpad)
- Display manager: lightdm (default)
- Made a user with admin rights
- Added additional software: just a `guake` package just for test (located in Terminals)
- Install

Got error:
```
2018-12-11 19:30 : Begin base install
==> Creating install root at /mnt
==> Installing packages to /mnt
pacman: unrecognized option '--overwrite'
==> ERROR: Failed to install packages to new root
2018-12-11 19:31 : Install failed: please report to developer
```

**Comment by noraj** [comment] 2018-12-31 19:11
Yeah, seems I got this error with LTS kernel. The code must be using `-f` but can't find it.

**Comment by Spheerys** [comment] 2019-02-07 09:00
Is this nice Arch installer is alive or not ?

**Comment by Spheerys** [comment] 2019-02-07 09:47
Finally I can't make another install because this bug, even by following [my own comment](https://github.com/deadhead420/anarchy-linux/issues/753#issuecomment-439398669) !
Did you get robust workaround to install Anarchy, even with minimal package ?

**Comment by noraj** [comment] 2019-02-07 19:15
@Spheerys What it I deed was install a true archlinux, see my guides:

+ The rather unusual, opinionated and commented ArchLinux installation : https://rawsec.ml/en/unusual-archlinux-installation/
+ ArchLinux installation in VirtualBox : https://rawsec.ml/en/archlinux-installation-in-virtualbox/

All those installer are so bugged and unmaintained.

**Comment by JustMeErazem** [comment] 2019-02-08 06:29
@noraj Love the first tutorial, thank you very much :)

**Comment by TheNekromate** [comment] 2019-02-22 08:19
I have the same issue when i try instaling the System with KDE and Zen Kernel

**Comment by JustMeErazem** [comment] 2019-02-25 16:08
@mbalc Try the [latest 1.0.2 iso](https://www.anarchylinux.org/download/), works great in VirtualBox for me.

**Comment by demure** [comment] 2019-04-04 02:20
I got the same issue with anarchy-cli-1.0.2-x86_64.iso while attempting to install on bare metal.
In this case the m.2 slot of a thinkpad x280.

Unfortunetly the log file doesn't really pin down the exact point at which the failure happens, which appears to be when a brief error comes up prior the UI for selecting the arch base.

**Comment by marceloperini** [comment] 2019-05-02 15:55
This was fixed on anarchy-cli-1.0.3-x86_64 version.

**Comment by jesusrp98** [comment] 2019-05-30 21:09
Just tried installing Anarchy using the `anarchy-cli-1.0.3-x86_64 ` version, and I'm getting the same error :/

**Comment by PandaFoss** [comment] 2019-05-30 21:27
@jesusrp98 Be more detailed to help you.

**Comment by jesusrp98** [comment] 2019-05-30 23:16
Tried to install with non-lts Linux kernel & installer returns the `Failed to install packages to new root` message.
Tried in a virtual machine, with same results.

**Comment by PandaFoss** [comment] 2019-05-31 00:37
> Tried to install with non-lts Linux kernel & installer returns the `Failed to install packages to new root` message.

That error is very comprehensive. I think the original issue was solved. If so, I suggest closing it (@mbalc ).
@jesusrp98 - In your case, check the last lines of the file by executing `tail /tmp/anarchy.log` and open a new issue if you require it.
I think that we can maintain order.

**Comment by jesusrp98** [comment] 2019-05-31 10:03
Of course, going to do a comprehensive test of this issue in a virtual envirioment, and then open, if neccesary, a new issue with the results.
Thank you very much.

**Comment by jesusrp98** [comment] 2019-05-31 10:55
Already opened a new issue. Check #794 for more details.

**Comment by JustMeErazem** [comment] 2019-08-13 13:58
Just tested with the latest 1.0.4 release, without updating, using most of the same packages as you and the base kernel. Works great, so @condor2 this one can probably be closed as well.

**Closed** 2019-08-14 04:39 UTC
