### ISSUE TITLE
Add Chinese support?

### ISSUE THREAD

**Issue by efreeking** [deadhead420/anarchy-linux#45] opened 2016-06-28 09:26 UTC
Is it possible to add the chinese support for arch-linux-anywhere?
I means that the ArhLinux Anywhere can display the Chinese language, so that the Chinese linuxer are able to take the advantage of the Archlinux Anywhere.

**Comment by condor2** [comment] 2016-06-29 19:43
yes, but need someone to translate in chinese

**Comment by deadhead420** [comment] 2016-06-30 10:49
Yes, are you able to translate?

**Comment by efreeking** [comment] 2016-07-01 08:04
I can  do the translation. I will do it later.

**Comment by deadhead420** [comment] 2016-07-13 10:29
Lol! Check the wiki! There aren't any AUR helpers in the arch repos....
Also to search packages use 'pacman -Ss'...

If you want to install yaourt there are two ways. 1. Install it from the
AUR with makepkg like it is meant to be. If you don't know how to use
makepkg you shouldn't be using the AUR at all. 2. Add the arch linux French
unofficial repos and install it with pacman.

**Comment by deadhead420** [comment] 2016-07-13 10:34
Although I urge you to learn makepkg here is the easy way.

Edit the file(as root/sudo): /etc/pacman.conf

All the way at the bottom add 3 lines:

[archlinuxfr]
Server = http://repo.archlinux.fr/$arch
SigLevel = Never

Save the file and exit
This will add the unofficial French repos to your pacman conf allowing you
to install packages from the French repo. This means you can install yaourt
or other aur helpers using pacman..

Next simply run:

sudo pacman -Sy yaourt

However like I said this is the total noob way and I urge you to use
makepkg because its super easy and the arch way.
On Jul 13, 2016 6:28 AM, "Dylan Schacht" <deadhead3492@gmail.com> wrote:

Lol! Check the wiki! There aren't any AUR helpers in the arch repos....
Also to search packages use 'pacman -Ss'...

If you want to install yaourt there are two ways. 1. Install it from the
AUR with makepkg like it is meant to be. If you don't know how to use
makepkg you shouldn't be using the AUR at all. 2. Add the arch linux French
unofficial repos and install it with pacman.

**Comment by efreeking** [comment] 2016-07-26 16:39
I had used the arch-linux-anywhere to make the arch-anywhere-2.2.3.iso, I tested it in the VirtualBox, and found that the Chinese words appear as black squares if I use the Chinese ui.
I think that because the wrong locale and miss of the Chinese font.
Wait for your improve!

**Comment by condor2** [comment] 2016-07-28 08:00
The script isn`t updated for chinese :)

**Comment by faddat** [comment] 2016-07-31 09:34
So what I was going to say was that actually all of the versions of Arch Linux anywhere should probably include cjk font support. When I install right now I begin with just plain boxes where there should be Chinese letters and Chinese letters are much better than just plain boxes.

**Comment by deadhead420** [comment] 2016-08-07 06:34
Working on it... Trying to figure it out.... It seems the framebuffer doesn't support Chinese characters. Need to figure out a work around to support Chinese fonts... If anyone has any input on how this can be done (without using xorg) let me know.

**Comment by deadhead420** [comment] 2016-08-16 00:42
Well its not pretty but I've finally figured out. After banging my head over this for the past month I've finally figured out how to get chinese characters to display in console only. I've managed to get fbterm working and am playing around with the fonts to get something which looks good. Not to say I won't run into anymore issues because its highly likely. But for now I have chinese characters working correctly in fbterm.

**Comment by deadhead420** [comment] 2016-09-07 20:39
Still working on this but its turned out to be much harder than I thought. I've got fbterm working in a vbox system however not on the ISO. Turns out the default archiso kernel does not have support for framebuffer devices.... SO. fbterm will not work no matter what I do. Thinking I should ditch the archiso entirely and start fresh creating my own ISO with my own kernel.

**Comment by tydlwav** [comment] 2017-03-01 00:18
I believe I can help with the translation. How can I get involved?

**Comment by deadhead420** [comment] 2017-03-01 00:30
@tydlwav That would be great... The problem I'm having is the Chinese characters are not being displayed correctly in the framebuffer. So what needs to be done is figuring out how to get the characters to display in the framebuffer. I know this can be done by getting fbterm to work but I was unable to get it working on the ISO... If you want to give it a shot you can download the latest arch-anywhere.iso from arch-anywhere.org 

The chinese translation can be found at /usr/share/arch-anywhere/lang/arch-installer-chinese.conf
As you can see in this photo The characters are not displayed and are instead replaced with boxes:
http://imgur.com/a/gtpDP

What needs to be figured out is how to get them to display on the iso...

**Comment by deadhead420** [comment] 2017-03-01 00:32
I spent hours trying to get this to work to no avail.

**Comment by tydlwav** [comment] 2017-03-01 00:50
From my experience, this might be a problem of the Chinese fonts used(not using equal width fonts). It might be because we are using the wrong encoding. I am not sure. I would need to investigate into it further. I guess if we could get tty to output Chinese, we could get the script to do the same.

**Comment by deadhead420** [comment] 2017-03-01 00:53
Yeah thats all it boils down to really. If tty can output Chinese it will work in the script too. I know that the problem is the fonts but no matter what I do I can't find a font which works.

**Comment by deadhead420** [comment] 2017-03-01 00:54
Also I've been able to get Chinese to display in the tty through fbterm on a fresh arch install. However no matter what I do I can't get fbterm to work on the archiso

**Comment by tydlwav** [comment] 2017-03-01 01:05
Did you try changing the locale into something like zh_CN.UTF8?

**Comment by deadhead420** [comment] 2017-03-01 01:06
Yep. I generate the locale for every language when creating the ISO and the locale is set at the top of each translation file. I know its the font I just can't find a working font.

**Comment by tydlwav** [comment] 2017-03-01 01:13
Hmm. I'll look for one that may work. Did you try the wqy-zenhei fonts?

**Comment by deadhead420** [comment] 2017-03-01 01:23
I'm pretty sure I did yes. But it has been awhile so I should probably mess around with it again

**Comment by deadhead420** [comment] 2017-03-01 01:35
This might sound a bit dumb lol but I have no clue which setfont command to run to apply the chinese font

**Comment by deadhead420** [comment] 2017-03-01 01:36
for example... Normally to set a font I would run:

setfont ter-v16n

**Comment by deadhead420** [comment] 2017-03-01 01:46
Nevermind. Now I remember why it wont work. I don't think wqy-zenhei is a console font. In order to get it working I would need xorg or fbterm

**Comment by deadhead420** [comment] 2017-03-01 01:46
As far as I know there are no console fonts which display Chinese.

**Comment by tydlwav** [comment] 2017-03-01 01:55
I'm still setting up my Arch. I'll try some tutorials in Chinese and see if they work.

**Comment by tydlwav** [comment] 2017-03-01 01:55
Sadly that would be a few days later. School's pretty intense.

**Comment by deadhead420** [comment] 2017-03-01 02:02
No worries. I'm working on it now but it has proven to be very tricky.

**Comment by deadhead420** [comment] 2017-03-01 05:02
FINALLY I think I finally figured this shit out after hours of banging my head..... Turns out I needed uvesafb drivers to get fbterm working. I've already got this added into the ISO

**Comment by deadhead420** [comment] 2017-03-01 07:35
Now I have fbterm working but of course its always a problem. Now no matter what I do I can't get my custom colors for the installer to work......

**Comment by deadhead420** [comment] 2017-03-01 09:37
Fuck fbterm.... I'm done trying. It works but its literally impossible to change the framebuffer color scheme. I've been searching google for hours, I've even gone as far as the 5th page of results on google. Fbterm is a piece of shit, I've wasted way too much time on it. It works, but I won't be able to have my custom color sheme so it isn't even worth it for me. The only thing I can think of from here to get Chinese working would be another framebuffer terminal emulator which supports the escape sequence codes for my color scheme, or using xorg server which I would rather not do because it will add 150+MB to the ISO.

**Comment by tydlwav** [comment] 2017-03-01 11:25
That's a shame. I'm glad you can get the fonts working, though. Chinese has always been a fuss. I remember using wine with Chinese software and everything comes up as unreadable blocks. Chinese support is probably the only reason for me to not ditch Windows completely.

**Comment by faddat** [comment] 2017-03-01 12:17
Chinese support for any OS tends to be lacking.  These days I find linux
approximately as good as windows.  Can I help you get your machine set up?

faddat@gmail.com

oh, and if you live in china/ read a lot of Chinese/ keep in touch with a
lot of Chinese people, QQ could be something missing from Linux.  I hate
that.


oh, and @deadhead420, @crypto-hippie says hi.  Oh, and we are putting your
arch distro on a router.  And selling it at router.dawn-project.com.

:),.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by tydlwav** [comment] 2017-03-01 12:52
Thanks for the offering, but the only problem now is that my high school's Internet need logging in, and I live in the dorm without access to wired Internet. I find it frustrating to get the Internet working through the install, so I'm waiting till I get back home in the weekend.

**Comment by deadhead420** [comment] 2017-03-01 19:51
I think I found a work around but its very hackish... I'm going to make it so fbterm will only run if chinese is selected and it won't have the color theme I use with all other languages. This will allow me to support chinese without sacrificing my custom color scheme

**Comment by deadhead420** [comment] 2017-03-01 23:25
Giving up on this for now... Have wasted way too much time trying to get this to work. My brain is fried from it.

**Comment by JustMeErazem** [comment] 2019-08-22 21:22
Closing since this issue is really outdated and there doesn't seem to be any progress in translating.

**Closed by JustMeErazem** 2019-08-22 21:22 UTC
Labels: translation, wontfix
